language: generic

sudo: required

services:
  - docker

addons:
  apt:
    sources:
      - debian-sid
    packages:
      - shellcheck

script:
  - "shellcheck scripts/*"
  - "./dev prod &"
  - "./dev ci"

deploy:
  provider: script
  script: scripts/purge-cache.sh
  on:
    branch: master

