[build]
  command = "yarn run build:prod"
  publish = "dist"

[build.environment]
  YARN_VERSION = "3.2.1"

# Plausible
[[redirects]]
  from = "/alphonso-mango/js/script.js"
  to = "https://plausible.io/js/script.js"
  status = 200
[[redirects]]
  from = "/alphonso-mango/api/event"
  to = "https://plausible.io/api/event"
  status = 200
