name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - name: Get the Yarn cache path
        id: yarn-cache-path
        run: echo "::set-output name=path::$(yarn config get cacheFolder)"
      - uses: actions/cache@v3
        with:
          path: ${{ steps.yarn-cache-path.outputs.path }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install packages
        run: yarn install --immutable
      - name: Check formatting
        run: yarn run format:check
      - name: Lint the code
        run: yarn run lint
      - name: Start the server
        run: yarn run start:prod &
        env:
          MOCK_HEADLINES: 1
      - name: Run tests
        run: yarn run test:ci
        timeout-minutes: 3
